### ISSUE TITLE
Only last event will be triggered in Edge/IE

### ISSUE THREAD

**Issue by hellow554** [byjg/jquery-sse#8]
When you send a contiguous stream of events (instead of calling a script over and over again), only the last one will be triggered. This is not in sync with Firefox/Chrome and not as I expect it.

**Comment by byjg** [comment]
Could you provide a simple example for me?

**Comment by hellow554** [comment]
var sse = $.SSE("test.php", {
        events: {
            first: function(e) {
                console.info("FIRST");
            },
            second: function(e) {
                console.info("SECOND");
            }
        }
    });
    sse.start();

Message should be somewhat like this:

    event: first
    data: FOO

    event: second
    data: BAR

**Comment by byjg** [comment]
Thanks! I'll work on it today later.

**Comment by byjg** [comment]
Hello, sorry for my delay.

The problem seems related with the Ajax fallback. The Ajax wait to process the event only after read all document. I modified the Ajax method to support text streaming. 

I did this change in the branch https://github.com/byjg/jquery-sse/tree/jquery-sse-8 . Could you test for me in your environment to see if it is OK? (Do not use the minified version).

**Comment by byjg** [comment]
Any comment? Can I close this?

**Comment by byjg** [comment]
Closing issue.
